# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

boolean 布尔型 0，1
float 浮点型
int 整型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [3]:
A=[]
for x in range(100):
    A.append(x*(-1)**(x-1))
int(sum(A))

50

1.3  将字符串 s="yoyo" 转换成列表

In [6]:
s='yoyo'
p=[str(i) for i in s]
print(p)

['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的
        
        range(1,100)建立含有数字1~99的列表
        [2::3]切片操作，省略结尾，为从第三个数开始取数，步长为3，直到最后，取得的是3~99中3的倍数
        [-10:]切片操作，在前面的基础上从倒数第十个数开始取数，直到最后，取得的是72~99之间3的倍数
        

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [2]:
class stock:
    def __init__(self,stockname,high,close): #初始化init实例，参数包括股票名称、最高价、最低价
        self.stockname = stockname
        self.high = high
        self.close = close
    def diff(self): #定义求差值函数
        return {self.stockname+'_dif':self.high-self.close}
stockone = stock('one',15,7)
print(stockone.diff())
stocktwo = stock('two',66,20)
print(stocktwo.diff())

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [3]:
print('数据转置：transpose() 查看列名：DataFrame.cloumns')

数据转置：transpose() 查看列名：DataFrame.cloumns


3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [4]:
import pandas as pd
import numpy as np
stock = pd.read_excel('sz50.xlsx',sheetname='600029.XSHG',index_col='datetime') #读取600029数据
close = np.array(stock.close) #转化数据格式为array

In [5]:
import talib as ta
data = ta.EMA(close,timeperiod=10) #计算EMA，周期为10
print(data[-5:]) #返回最后5个值

[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [7]:
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {} #初始化空白字典用于内置数据
for i in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=i, index_col='datetime')
    data_dict[i] = data.loc[:]
P = pd.Panel(data_dict)
print(P)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [8]:
stock_numpy = np.array(P)
print(stock_numpy.shape)
print(stock_numpy[:,-20:,0])

(3, 215, 5)
[[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
   14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
 [  8.53   8.56   8.62   8.88   9.25   9.24   9.43   9.25   9.02   9.15
    9.63   9.5    9.9    9.97   9.96   9.49   9.68   9.61   9.63   9.8 ]
 [134.83 134.56 137.5  143.18 143.48 144.15 143.61 143.65 144.35 143.36
  146.41 144.71 148.56 156.53 157.12 157.72 154.99 163.52 168.58 169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [8]:
import numpy as np
A=np.mat(range(0,25)).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
